server:
  port: 9001

spring:
  application:
    name: user-service
  profiles:
    active: qa
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/user-service
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: dev
welcome:
  message: Welcome to EagleSoft!!!

---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/user-service-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: qa
welcome:
  message: Welcome to EagleSoft!!!
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/user-service-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: prod
welcome:
  message: Welcome to EagleSoft!!!
---

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---
eureka:
  instance:
    hostname: localhost

